-- 2026-05-07: shifts.series_id — link the rows generated by one
-- /schedule/new submission so we can later edit / cancel them as a
-- group ("apply to this shift only" / "this and future" / "all in
-- series"). The schedule form's cartesian product (dates × customers
-- × reps) already writes N independent rows; this lets us tie them
-- back together.
--
-- Nullable because:
--   1. Existing shifts pre-date this column.
--   2. A one-off shift (single day, single customer, single rep) is
--      not really a "series" — leaving series_id NULL makes that
--      explicit instead of forcing a meaningless uuid.
--
-- Run once in Supabase → SQL Editor. Safe to re-run.

ALTER TABLE public.shifts
  ADD COLUMN IF NOT EXISTS series_id uuid NULL;

CREATE INDEX IF NOT EXISTS shifts_series_id_idx
  ON public.shifts (series_id)
  WHERE series_id IS NOT NULL;
